apiVersion: v1
kind: Namespace
metadata:
  name: audiomuse-all-in-one

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiomuse-all-in-one-deployment
  namespace: audiomuse-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiomuse-all-in-one
  template:
    metadata:
      labels:
        app: audiomuse-all-in-one
    spec:
      containers:
      - name: audiomuse-all-in-one
        # IMPORTANT: Replace this with the full path to your image in your local registry
        image: 192.168.3.99:5000/audiomuse-ai-server:local
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 8080
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: audiomuse-all-in-one-service
  namespace: audiomuse-all-in-one
spec:
  selector:
    app: audiomuse-all-in-one
  type: LoadBalancer
  loadBalancerIP: 192.168.3.77
  ports:
    - name: react-frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: go-backend
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: python-core
      protocol: TCP
      port: 8000
      targetPort: 8000