apiVersion: v1
kind: Namespace
metadata:
  name: audiomuse-all-in-one

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiomuse-config-pvc
  namespace: audiomuse-all-in-one
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiomuse-music-pvc
  namespace: audiomuse-all-in-one
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiomuse-all-in-one-deployment
  namespace: audiomuse-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiomuse-all-in-one
  template:
    metadata:
      labels:
        app: audiomuse-all-in-one
    spec:
      containers:
      - name: audiomuse-all-in-one
        image: 192.168.3.99:5000/audiomuse-ai-server:local
        ports:
        - containerPort: 8080  # Music Server Backend
        - containerPort: 3000  # Music Server Frontend
        volumeMounts:
        - name: config-storage
          mountPath: /config  # ALL DATABASES GO HERE
        - name: music-storage
          mountPath: /music   # MUSIC FILES GO HERE
      volumes:
      - name: config-storage
        persistentVolumeClaim:
          claimName: audiomuse-config-pvc
      - name: music-storage
        persistentVolumeClaim:
          claimName: audiomuse-music-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: audiomuse-service
  namespace: audiomuse
spec:
  selector:
    app: audiomuse
  type: LoadBalancer
  loadBalancerIP: 192.168.3.77
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080

